server:
  port: 8081
  error:
    include-binding-errors: always

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: user
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/analysis_system
    username: postgres
    password: 12345678