server:
  port: 8084
  error:
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/analysis_system
    username: postgres
    password: 12345678

security:
  oauth2:
    client:
      client-id: atsId
      client-secret: atsSecret
      signing-key: atsSigningKey
      token-validity-seconds: 3600
      refresh-token-validity-seconds: 1500
